//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.ServiceAmaguaCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", ConfigurationName="ServiceAmaguaCliente.AmkPagoExternoWS")]
    public interface AmkPagoExternoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/registra" +
            "rPagoRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/registra" +
            "rPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.registrarPagoResponse registrarPago(Practica.ServiceAmaguaCliente.registrarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/registra" +
            "rPagoRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/registra" +
            "rPagoResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.registrarPagoResponse> registrarPagoAsync(Practica.ServiceAmaguaCliente.registrarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/anularPa" +
            "goRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/anularPa" +
            "goResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.anularPagoResponse anularPago(Practica.ServiceAmaguaCliente.anularPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/anularPa" +
            "goRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/anularPa" +
            "goResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.anularPagoResponse> anularPagoAsync(Practica.ServiceAmaguaCliente.anularPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/arqueoPa" +
            "gosRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/arqueoPa" +
            "gosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.arqueoPagosResponse arqueoPagos(Practica.ServiceAmaguaCliente.arqueoPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/arqueoPa" +
            "gosRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/arqueoPa" +
            "gosResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.arqueoPagosResponse> arqueoPagosAsync(Practica.ServiceAmaguaCliente.arqueoPagosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "PagosRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "PagosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.consultaPagosResponse consultaPagos(Practica.ServiceAmaguaCliente.consultaPagosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "PagosRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "PagosResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaPagosResponse> consultaPagosAsync(Practica.ServiceAmaguaCliente.consultaPagosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "rSaldoRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "rSaldoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.consultarSaldoResponse consultarSaldo(Practica.ServiceAmaguaCliente.consultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "rSaldoRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "rSaldoResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultarSaldoResponse> consultarSaldoAsync(Practica.ServiceAmaguaCliente.consultarSaldoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "InfoClienteRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "InfoClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Practica.ServiceAmaguaCliente.consultaInfoClienteResponse consultaInfoCliente(Practica.ServiceAmaguaCliente.consultaInfoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "InfoClienteRequest", ReplyAction="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/AmkPagoExternoWS/consulta" +
            "InfoClienteResponse")]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaInfoClienteResponse> consultaInfoClienteAsync(Practica.ServiceAmaguaCliente.consultaInfoClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class pagoInputType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codTransField;
        
        private decimal documentoField;
        
        private bool documentoFieldSpecified;
        
        private int inmCodigoField;
        
        private double valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codTrans {
            get {
                return this.codTransField;
            }
            set {
                this.codTransField = value;
                this.RaisePropertyChanged("codTrans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentoSpecified {
            get {
                return this.documentoFieldSpecified;
            }
            set {
                this.documentoFieldSpecified = value;
                this.RaisePropertyChanged("documentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int inmCodigo {
            get {
                return this.inmCodigoField;
            }
            set {
                this.inmCodigoField = value;
                this.RaisePropertyChanged("inmCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class inmuebleConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codClienteField;
        
        private string correoField;
        
        private string direccionField;
        
        private string direccionInmuebleField;
        
        private string docIdentificacionField;
        
        private int inmCodigoField;
        
        private string nombreClienteField;
        
        private string telefonoField;
        
        private string tipoIdentificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
                this.RaisePropertyChanged("codCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccionInmueble {
            get {
                return this.direccionInmuebleField;
            }
            set {
                this.direccionInmuebleField = value;
                this.RaisePropertyChanged("direccionInmueble");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string docIdentificacion {
            get {
                return this.docIdentificacionField;
            }
            set {
                this.docIdentificacionField = value;
                this.RaisePropertyChanged("docIdentificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int inmCodigo {
            get {
                return this.inmCodigoField;
            }
            set {
                this.inmCodigoField = value;
                this.RaisePropertyChanged("inmCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
                this.RaisePropertyChanged("tipoIdentificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class inmuebleCabeceraRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRespuestaField;
        
        private string idSesionField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idSesion {
            get {
                return this.idSesionField;
            }
            set {
                this.idSesionField = value;
                this.RaisePropertyChanged("idSesion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class inmuebleRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private inmuebleCabeceraRes cabeceraField;
        
        private inmuebleConsulta inmuebleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public inmuebleCabeceraRes cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public inmuebleConsulta inmueble {
            get {
                return this.inmuebleField;
            }
            set {
                this.inmuebleField = value;
                this.RaisePropertyChanged("inmueble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class facturaConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double baseGravableField;
        
        private double baseNoGravableField;
        
        private int consecutivoField;
        
        private int documentoField;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private double ivaField;
        
        private double pagadoField;
        
        private int periodoField;
        
        private double saldoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double baseGravable {
            get {
                return this.baseGravableField;
            }
            set {
                this.baseGravableField = value;
                this.RaisePropertyChanged("baseGravable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double baseNoGravable {
            get {
                return this.baseNoGravableField;
            }
            set {
                this.baseNoGravableField = value;
                this.RaisePropertyChanged("baseNoGravable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double iva {
            get {
                return this.ivaField;
            }
            set {
                this.ivaField = value;
                this.RaisePropertyChanged("iva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double pagado {
            get {
                return this.pagadoField;
            }
            set {
                this.pagadoField = value;
                this.RaisePropertyChanged("pagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class cuotasConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double interesField;
        
        private int periodoField;
        
        private double saldoField;
        
        private double totalField;
        
        private double valorAplicadoField;
        
        private double valorAplicadoInteresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double interes {
            get {
                return this.interesField;
            }
            set {
                this.interesField = value;
                this.RaisePropertyChanged("interes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double valorAplicado {
            get {
                return this.valorAplicadoField;
            }
            set {
                this.valorAplicadoField = value;
                this.RaisePropertyChanged("valorAplicado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double valorAplicadoInteres {
            get {
                return this.valorAplicadoInteresField;
            }
            set {
                this.valorAplicadoInteresField = value;
                this.RaisePropertyChanged("valorAplicadoInteres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class facturacionCabeceraRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRespuestaField;
        
        private string idSesionField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idSesion {
            get {
                return this.idSesionField;
            }
            set {
                this.idSesionField = value;
                this.RaisePropertyChanged("idSesion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class saldoRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double baseGravableTotalField;
        
        private double baseNGMasSaldoCuotasField;
        
        private double baseNoGravableTotalField;
        
        private facturacionCabeceraRes cabeceraField;
        
        private cuotasConsulta[] cuotasConvenioField;
        
        private facturaConsulta[] facturasField;
        
        private double ivaTotalField;
        
        private double saldoTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double baseGravableTotal {
            get {
                return this.baseGravableTotalField;
            }
            set {
                this.baseGravableTotalField = value;
                this.RaisePropertyChanged("baseGravableTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double baseNGMasSaldoCuotas {
            get {
                return this.baseNGMasSaldoCuotasField;
            }
            set {
                this.baseNGMasSaldoCuotasField = value;
                this.RaisePropertyChanged("baseNGMasSaldoCuotas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double baseNoGravableTotal {
            get {
                return this.baseNoGravableTotalField;
            }
            set {
                this.baseNoGravableTotalField = value;
                this.RaisePropertyChanged("baseNoGravableTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public facturacionCabeceraRes cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuotasConvenio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public cuotasConsulta[] cuotasConvenio {
            get {
                return this.cuotasConvenioField;
            }
            set {
                this.cuotasConvenioField = value;
                this.RaisePropertyChanged("cuotasConvenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public facturaConsulta[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
                this.RaisePropertyChanged("facturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double ivaTotal {
            get {
                return this.ivaTotalField;
            }
            set {
                this.ivaTotalField = value;
                this.RaisePropertyChanged("ivaTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double saldoTotal {
            get {
                return this.saldoTotalField;
            }
            set {
                this.saldoTotalField = value;
                this.RaisePropertyChanged("saldoTotal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class arqueoRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pagoCabeceraRes cabeceraField;
        
        private double valorAnuladoField;
        
        private double valorAplicadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pagoCabeceraRes cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double valorAnulado {
            get {
                return this.valorAnuladoField;
            }
            set {
                this.valorAnuladoField = value;
                this.RaisePropertyChanged("valorAnulado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double valorAplicado {
            get {
                return this.valorAplicadoField;
            }
            set {
                this.valorAplicadoField = value;
                this.RaisePropertyChanged("valorAplicado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class pagoCabeceraRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRespuestaField;
        
        private string idSesionField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idSesion {
            get {
                return this.idSesionField;
            }
            set {
                this.idSesionField = value;
                this.RaisePropertyChanged("idSesion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class arqueoInputType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaFinalField;
        
        private string fechaInicialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("fechaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
                this.RaisePropertyChanged("fechaInicial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class pagoConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoPagoField;
        
        private decimal documentoField;
        
        private bool documentoFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int inmCodigoField;
        
        private double valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPago {
            get {
                return this.codigoPagoField;
            }
            set {
                this.codigoPagoField = value;
                this.RaisePropertyChanged("codigoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentoSpecified {
            get {
                return this.documentoFieldSpecified;
            }
            set {
                this.documentoFieldSpecified = value;
                this.RaisePropertyChanged("documentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int inmCodigo {
            get {
                return this.inmCodigoField;
            }
            set {
                this.inmCodigoField = value;
                this.RaisePropertyChanged("inmCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/")]
    public partial class pagoRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pagoCabeceraRes cabeceraField;
        
        private pagoConsulta[] pagosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pagoCabeceraRes cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pagos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public pagoConsulta[] pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
                this.RaisePropertyChanged("pagos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPago", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class registrarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.pagoInputType pagoEntrada;
        
        public registrarPagoRequest() {
        }
        
        public registrarPagoRequest(string Usuario, string Password, Practica.ServiceAmaguaCliente.pagoInputType pagoEntrada) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.pagoEntrada = pagoEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPagoResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class registrarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.pagoRespuesta @return;
        
        public registrarPagoResponse() {
        }
        
        public registrarPagoResponse(Practica.ServiceAmaguaCliente.pagoRespuesta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anularPago", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class anularPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTrans;
        
        public anularPagoRequest() {
        }
        
        public anularPagoRequest(string Usuario, string Password, int codigoPago, string motivo, string codTrans) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.codigoPago = codigoPago;
            this.motivo = motivo;
            this.codTrans = codTrans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anularPagoResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class anularPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.pagoCabeceraRes @return;
        
        public anularPagoResponse() {
        }
        
        public anularPagoResponse(Practica.ServiceAmaguaCliente.pagoCabeceraRes @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="arqueoPagos", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class arqueoPagosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada;
        
        public arqueoPagosRequest() {
        }
        
        public arqueoPagosRequest(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.arqueoEntrada = arqueoEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="arqueoPagosResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class arqueoPagosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.arqueoRespuesta @return;
        
        public arqueoPagosResponse() {
        }
        
        public arqueoPagosResponse(Practica.ServiceAmaguaCliente.arqueoRespuesta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPagos", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultaPagosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada;
        
        public consultaPagosRequest() {
        }
        
        public consultaPagosRequest(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.arqueoEntrada = arqueoEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaPagosResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultaPagosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.pagoRespuesta @return;
        
        public consultaPagosResponse() {
        }
        
        public consultaPagosResponse(Practica.ServiceAmaguaCliente.pagoRespuesta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldo", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultarSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int inmCodigo;
        
        public consultarSaldoRequest() {
        }
        
        public consultarSaldoRequest(string Usuario, string Password, int inmCodigo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.inmCodigo = inmCodigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldoResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultarSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.saldoRespuesta @return;
        
        public consultarSaldoResponse() {
        }
        
        public consultarSaldoResponse(Practica.ServiceAmaguaCliente.saldoRespuesta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaInfoCliente", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultaInfoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int inmCodigo;
        
        public consultaInfoClienteRequest() {
        }
        
        public consultaInfoClienteRequest(string Usuario, string Password, int inmCodigo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.inmCodigo = inmCodigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaInfoClienteResponse", WrapperNamespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", IsWrapped=true)]
    public partial class consultaInfoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.pagoExterno.recaudos.ws.servicios.amerika.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Practica.ServiceAmaguaCliente.inmuebleRespuesta @return;
        
        public consultaInfoClienteResponse() {
        }
        
        public consultaInfoClienteResponse(Practica.ServiceAmaguaCliente.inmuebleRespuesta @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AmkPagoExternoWSChannel : Practica.ServiceAmaguaCliente.AmkPagoExternoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmkPagoExternoWSClient : System.ServiceModel.ClientBase<Practica.ServiceAmaguaCliente.AmkPagoExternoWS>, Practica.ServiceAmaguaCliente.AmkPagoExternoWS {
        
        public AmkPagoExternoWSClient() {
        }
        
        public AmkPagoExternoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmkPagoExternoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmkPagoExternoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmkPagoExternoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.registrarPagoResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.registrarPago(Practica.ServiceAmaguaCliente.registrarPagoRequest request) {
            return base.Channel.registrarPago(request);
        }
        
        public Practica.ServiceAmaguaCliente.pagoRespuesta registrarPago(string Usuario, string Password, Practica.ServiceAmaguaCliente.pagoInputType pagoEntrada) {
            Practica.ServiceAmaguaCliente.registrarPagoRequest inValue = new Practica.ServiceAmaguaCliente.registrarPagoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.pagoEntrada = pagoEntrada;
            Practica.ServiceAmaguaCliente.registrarPagoResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).registrarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.registrarPagoResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.registrarPagoAsync(Practica.ServiceAmaguaCliente.registrarPagoRequest request) {
            return base.Channel.registrarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.registrarPagoResponse> registrarPagoAsync(string Usuario, string Password, Practica.ServiceAmaguaCliente.pagoInputType pagoEntrada) {
            Practica.ServiceAmaguaCliente.registrarPagoRequest inValue = new Practica.ServiceAmaguaCliente.registrarPagoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.pagoEntrada = pagoEntrada;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).registrarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.anularPagoResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.anularPago(Practica.ServiceAmaguaCliente.anularPagoRequest request) {
            return base.Channel.anularPago(request);
        }
        
        public Practica.ServiceAmaguaCliente.pagoCabeceraRes anularPago(string Usuario, string Password, int codigoPago, string motivo, string codTrans) {
            Practica.ServiceAmaguaCliente.anularPagoRequest inValue = new Practica.ServiceAmaguaCliente.anularPagoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.codigoPago = codigoPago;
            inValue.motivo = motivo;
            inValue.codTrans = codTrans;
            Practica.ServiceAmaguaCliente.anularPagoResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).anularPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.anularPagoResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.anularPagoAsync(Practica.ServiceAmaguaCliente.anularPagoRequest request) {
            return base.Channel.anularPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.anularPagoResponse> anularPagoAsync(string Usuario, string Password, int codigoPago, string motivo, string codTrans) {
            Practica.ServiceAmaguaCliente.anularPagoRequest inValue = new Practica.ServiceAmaguaCliente.anularPagoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.codigoPago = codigoPago;
            inValue.motivo = motivo;
            inValue.codTrans = codTrans;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).anularPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.arqueoPagosResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.arqueoPagos(Practica.ServiceAmaguaCliente.arqueoPagosRequest request) {
            return base.Channel.arqueoPagos(request);
        }
        
        public Practica.ServiceAmaguaCliente.arqueoRespuesta arqueoPagos(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            Practica.ServiceAmaguaCliente.arqueoPagosRequest inValue = new Practica.ServiceAmaguaCliente.arqueoPagosRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.arqueoEntrada = arqueoEntrada;
            Practica.ServiceAmaguaCliente.arqueoPagosResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).arqueoPagos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.arqueoPagosResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.arqueoPagosAsync(Practica.ServiceAmaguaCliente.arqueoPagosRequest request) {
            return base.Channel.arqueoPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.arqueoPagosResponse> arqueoPagosAsync(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            Practica.ServiceAmaguaCliente.arqueoPagosRequest inValue = new Practica.ServiceAmaguaCliente.arqueoPagosRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.arqueoEntrada = arqueoEntrada;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).arqueoPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.consultaPagosResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultaPagos(Practica.ServiceAmaguaCliente.consultaPagosRequest request) {
            return base.Channel.consultaPagos(request);
        }
        
        public Practica.ServiceAmaguaCliente.pagoRespuesta consultaPagos(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            Practica.ServiceAmaguaCliente.consultaPagosRequest inValue = new Practica.ServiceAmaguaCliente.consultaPagosRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.arqueoEntrada = arqueoEntrada;
            Practica.ServiceAmaguaCliente.consultaPagosResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultaPagos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaPagosResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultaPagosAsync(Practica.ServiceAmaguaCliente.consultaPagosRequest request) {
            return base.Channel.consultaPagosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaPagosResponse> consultaPagosAsync(string Usuario, string Password, Practica.ServiceAmaguaCliente.arqueoInputType arqueoEntrada) {
            Practica.ServiceAmaguaCliente.consultaPagosRequest inValue = new Practica.ServiceAmaguaCliente.consultaPagosRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.arqueoEntrada = arqueoEntrada;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultaPagosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.consultarSaldoResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultarSaldo(Practica.ServiceAmaguaCliente.consultarSaldoRequest request) {
            return base.Channel.consultarSaldo(request);
        }
        
        public Practica.ServiceAmaguaCliente.saldoRespuesta consultarSaldo(string Usuario, string Password, int inmCodigo) {
            Practica.ServiceAmaguaCliente.consultarSaldoRequest inValue = new Practica.ServiceAmaguaCliente.consultarSaldoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.inmCodigo = inmCodigo;
            Practica.ServiceAmaguaCliente.consultarSaldoResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultarSaldo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultarSaldoResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultarSaldoAsync(Practica.ServiceAmaguaCliente.consultarSaldoRequest request) {
            return base.Channel.consultarSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultarSaldoResponse> consultarSaldoAsync(string Usuario, string Password, int inmCodigo) {
            Practica.ServiceAmaguaCliente.consultarSaldoRequest inValue = new Practica.ServiceAmaguaCliente.consultarSaldoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.inmCodigo = inmCodigo;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultarSaldoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica.ServiceAmaguaCliente.consultaInfoClienteResponse Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultaInfoCliente(Practica.ServiceAmaguaCliente.consultaInfoClienteRequest request) {
            return base.Channel.consultaInfoCliente(request);
        }
        
        public Practica.ServiceAmaguaCliente.inmuebleRespuesta consultaInfoCliente(string Usuario, string Password, int inmCodigo) {
            Practica.ServiceAmaguaCliente.consultaInfoClienteRequest inValue = new Practica.ServiceAmaguaCliente.consultaInfoClienteRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.inmCodigo = inmCodigo;
            Practica.ServiceAmaguaCliente.consultaInfoClienteResponse retVal = ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultaInfoCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaInfoClienteResponse> Practica.ServiceAmaguaCliente.AmkPagoExternoWS.consultaInfoClienteAsync(Practica.ServiceAmaguaCliente.consultaInfoClienteRequest request) {
            return base.Channel.consultaInfoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica.ServiceAmaguaCliente.consultaInfoClienteResponse> consultaInfoClienteAsync(string Usuario, string Password, int inmCodigo) {
            Practica.ServiceAmaguaCliente.consultaInfoClienteRequest inValue = new Practica.ServiceAmaguaCliente.consultaInfoClienteRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.inmCodigo = inmCodigo;
            return ((Practica.ServiceAmaguaCliente.AmkPagoExternoWS)(this)).consultaInfoClienteAsync(inValue);
        }
    }
}
