//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaServicioAmaguaOnline.ServiceAmagua {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAmagua.IConciliacionAmagua")]
    public interface IConciliacionAmagua {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacionAmagua/ic_generarArchivoTransacciones", ReplyAction="http://tempuri.org/IConciliacionAmagua/ic_generarArchivoTransaccionesResponse")]
        string ic_generarArchivoTransacciones(int usuario, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacionAmagua/ic_generarArchivoTransacciones", ReplyAction="http://tempuri.org/IConciliacionAmagua/ic_generarArchivoTransaccionesResponse")]
        System.Threading.Tasks.Task<string> ic_generarArchivoTransaccionesAsync(int usuario, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacionAmagua/GenerarArchivoTransaccionesOnLine", ReplyAction="http://tempuri.org/IConciliacionAmagua/GenerarArchivoTransaccionesOnLineResponse")]
        string GenerarArchivoTransaccionesOnLine(int usuario, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacionAmagua/GenerarArchivoTransaccionesOnLine", ReplyAction="http://tempuri.org/IConciliacionAmagua/GenerarArchivoTransaccionesOnLineResponse")]
        System.Threading.Tasks.Task<string> GenerarArchivoTransaccionesOnLineAsync(int usuario, string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConciliacionAmaguaChannel : pruebaServicioAmaguaOnline.ServiceAmagua.IConciliacionAmagua, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConciliacionAmaguaClient : System.ServiceModel.ClientBase<pruebaServicioAmaguaOnline.ServiceAmagua.IConciliacionAmagua>, pruebaServicioAmaguaOnline.ServiceAmagua.IConciliacionAmagua {
        
        public ConciliacionAmaguaClient() {
        }
        
        public ConciliacionAmaguaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConciliacionAmaguaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConciliacionAmaguaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConciliacionAmaguaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ic_generarArchivoTransacciones(int usuario, string ip) {
            return base.Channel.ic_generarArchivoTransacciones(usuario, ip);
        }
        
        public System.Threading.Tasks.Task<string> ic_generarArchivoTransaccionesAsync(int usuario, string ip) {
            return base.Channel.ic_generarArchivoTransaccionesAsync(usuario, ip);
        }
        
        public string GenerarArchivoTransaccionesOnLine(int usuario, string ip) {
            return base.Channel.GenerarArchivoTransaccionesOnLine(usuario, ip);
        }
        
        public System.Threading.Tasks.Task<string> GenerarArchivoTransaccionesOnLineAsync(int usuario, string ip) {
            return base.Channel.GenerarArchivoTransaccionesOnLineAsync(usuario, ip);
        }
    }
}
