//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public int id_empresa { get; set; }
        public int id_rol { get; set; }
        public string nombre_usuario { get; set; }
        public string nombre_completo { get; set; }
        public string tipo_identificacion { get; set; }
        public string numero_identificacion { get; set; }
        public string email { get; set; }
        public string ciudad { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public bool requiere_control_estacion_trabajo { get; set; }
        public bool requiere_token { get; set; }
        public bool token_habilitado { get; set; }
        public string estado_aplicacion { get; set; }
        public string estado_directorio_activo { get; set; }
        public Nullable<int> id_institucion_financiera { get; set; }
        public Nullable<int> id_imagen { get; set; }
        public Nullable<int> codigo_imagen { get; set; }
        public string descripcion_imagen { get; set; }
        public string telefono_celular { get; set; }
        public string tipo_usuario { get; set; }
        public Nullable<int> intentos_fallidos { get; set; }
        public Nullable<bool> clave_reestablecida { get; set; }
        public Nullable<int> agencia_origen { get; set; }
        public string email_responsable { get; set; }
    }
}
